#!/bin/sh
set -e
set -o pipefail
name="$1"
if [ -z "$name" ]; then
	>&2 echo missing 1st argument: pod name
	exit 1
fi
kubectl get pods --all-namespaces | grep $name | grep Running | head -n 1 | awk '{print $2}'
